server:
  port: 9933
spring:
  application:
    name: data-agent
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  profiles:
    active: private
  datasource:
    url: jdbc:postgresql://localhost:5432/data_agent_tutorial
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  ai:
    model:
      chat: openai
      embedding: openai
      image: none
      audio:
        speech: none
        transcription: none
      moderation: none
    openai:
      base-url: ${OPENAI_BASE_URL:}
      api-key: ${OPENAI_API_KEY:}
      chat:
        base-url: ${OPENAI_CHAT_BASE_URL:${OPENAI_BASE_URL:}}
        api-key: ${OPENAI_CHAT_API_KEY:${OPENAI_API_KEY:}}
        options:
          model: ${OPENAI_CHAT_MODEL:}
      embedding:
        base-url: ${OPENAI_EMBEDDING_BASE_URL:${OPENAI_BASE_URL:}}
        api-key: ${OPENAI_EMBEDDING_API_KEY:${OPENAI_API_KEY:}}
        options:
          model: ${OPENAI_EMBEDDING_MODEL:text-embedding-v4}
    vectorstore:
      pgvector:
        index-type: HNSW      # 2026 年主流的高性能索引
        distance-type: cosine_distance # 语义搜索常用的余弦相似度
        dimensions: 1024      # text-embedding-v4 维度，如果更换了嵌入模型需要删除vector_store表重建
        initialize-schema: true  # 不填dimensions其实也可以，但是这样很多人换了模型不知道要修改dimensions，spring ai会自动初始化向量维度
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: io.github.qifan777.server
  type-handlers-package: io.github.qifan777.server.shared.mybatis
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: input
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /openapi-ui
