server:
  port: 9933
spring:
  application:
    name: data-agent
  profiles:
    active: private
  datasource:
    url: jdbc:postgresql://localhost:5432/data_agent_tutorial
    username:
    password:
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      base-url: openai协议baseurl(不带v1)，例如 https://dashscope.aliyuncs.com/compatible-mode
      api-key:
      chat:
        options:
          model:
      embedding:
        options:
          model: text-embedding-v4（阿里的）
    vectorstore:
      pgvector:
        index-type: HNSW      # 2026 年主流的高性能索引
        distance-type: cosine_distance # 语义搜索常用的余弦相似度
        dimensions: 1024      # text-embedding-v4 维度，如果更换了嵌入模型需要删除vector_store表重建
        initialize-schema: true  # 不填dimensions其实也可以，但是这样很多人换了模型不知道要修改dimensions，spring ai会自动初始化向量维度
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: io.github.qifan777.server
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_uuid
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /openapi-ui
